spring:
  # 分布式配置中心 客户端
  cloud:
    config:
      # 配置服务中心的网址
      uri: http://localhost:8888
      # 配置文件名称的前缀
      name: itoken-zuul
      # 配置仓库的分支
      label: master
      # 配置文件的环境标识
      # dev：表示开发环境
      # test：表示测试环境
      # prod：表示生产环境
      profile: dev